# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-04 18:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('programmer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lookforjob',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
